name: enhanced_rag_system
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.10
  - pip
  
  # 基础科学计算
  - numpy>=1.21.0
  - scipy>=1.7.0
  - scikit-learn>=1.0.0
  - pandas>=1.3.0
  
  # 机器学习框架
  - pytorch>=1.12.0
  - torchvision
  - torchaudio
  
  # 文档处理
  - pillow>=9.0.0
  - opencv
  
  # 系统工具
  - psutil>=5.9.0
  
  # 通过pip安装的包
  - pip:
    # CAMEL框架和AI相关
    - camel-ai>=0.1.0
    - sentence-transformers>=2.2.0
    - transformers>=4.20.0
    
    # 文档处理增强
    - pypdf>=3.0.0
    - unstructured[pdf,image,tables,docx]>=0.10.0
    - python-docx>=0.8.11
    - docx2txt>=0.8
    - striprtf>=0.0.12
    - python-pptx>=0.6.21
    - openpyxl>=3.0.9
    - tabula-py>=2.5.0
    
    # 网络请求和爬虫
    - requests>=2.28.0
    - beautifulsoup4>=4.11.0
    - selenium>=4.0.0
    - lxml>=4.9.0
    
    # 环境和配置
    - python-dotenv>=0.19.0
    - colorama>=0.4.4
    - rich>=12.0.0
    
    # 数据处理
    - json5>=0.9.0
    
    # 评估和指标
    - rouge-score>=0.1.2
    - nltk>=3.7
    
    # 向量数据库
    - qdrant-client>=1.0.0
    - chromadb>=0.4.0
    
    # 知识图谱
    - neo4j>=5.0.0
    - networkx>=2.8.0
    
    # 监控和日志
    - agentops>=0.2.0
    - loguru>=0.6.0
    
    # 图像处理和OCR
    - pytesseract>=0.3.10
    - PyMuPDF>=1.23.0
    
    # 可选功能包
    - firecrawl-py>=0.0.5
    - duckduckgo-search>=3.0.0
    - wikipedia>=1.4.0
    - arxiv>=1.4.0
    - youtube-transcript-api>=0.5.0
    
    # 开发和测试工具
    - pytest>=7.0.0
    - black>=22.0.0
    - flake8>=4.0.0
    - tqdm>=4.64.0